### ISSUE TITLE
How to generate st.mat file for different size?

### ISSUE THREAD

**Issue by DarwinSenior** [ygaostu/Shearlet-Transform-TensorFlow#1]
Can I ask how to generate st.mat for a different size? 
I want to test this code for interpolating new light field but with a different shape.

**Comment by ygaostu** [comment]
Hi,

This is done by using the "software" of http://www.cs.tut.fi/~vagharsh/EPISparseRec.html

% Matlab code
addpath('./shearlets');
scalelvl = 1:4;
sys = constructShearlet([127, 127], scalelvl, [128, 608]); % im_h = 128, im_w = 608

Then, save "sys" into "st.mat".

**Comment by Adrian857857** [comment]
Hi，
There was an error with this link.
 http://www.cs.tut.fi/~vagharsh/EPISparseRec.html

Can you help me find a new link?

Best wishes
